Api part 2
SnowEx/snowexsql pull request #98
Opened 2024-08-01 21:54 UTC by micahjohnson150

* Added in some support for rasters. 
* Added in some simplifying of the results from `.all_*`
* Added in `from_unique_entries` which allows users to find options for a query theyre working on . Example:  what dates did specific surface area get collected. 
* Addresses #97

2024-08-01 22:45 UTC, jomey commented
Just a quick reminder to keep track of the changes and maybe start a manual CHANGELOG.md for now until I get back to #85 and automate this?

2024-08-05 19:37 UTC, micah-prime reviewed
I just had one suggestion that is a result of what I added being out of sync

2024-08-05 19:37 UTC, micah-prime commented on snowexsql/api.py
> +        return self.retrieve_single_value_result(result)
Good call

2024-08-05 19:37 UTC, micah-prime commented on snowexsql/api.py
>          return result
```suggestion
        return self.retrieve_single_value_result(result)
```

2024-08-05 19:39 UTC, micah-prime commented
@micahjohnson150 are we missing some commits? I don't see what you're referencing with 'Added in some support for rasters.'

2024-08-05 22:17 UTC, micahjohnson150 commented
@micah-prime you were correct. I hadnt pushed everything apparently and got my edits and commits mixed up lol. This should be everything I have.

2024-08-08 16:55 UTC, micah-prime commented on snowexsql/api.py
> +                session.close()
I don't think you need to call session lose. I believe the `db_session` should handle that

2024-08-08 16:56 UTC, micah-prime commented on snowexsql/api.py
> +        "utm_zone", "date_greater_equal", "date_less_equal", "value_greater_equal", 'value_less_equal',
Nice addition!

2024-08-08 16:56 UTC, micah-prime commented on requirements.txt
> +geopandas>=0.7,<2.0
WOOO!

2024-08-08 16:56 UTC, micah-prime commented on snowexsql/api.py
> +        #     kwargs.pop("resolution")
Can these comments go?

2024-08-08 16:56 UTC, micah-prime commented on snowexsql/api.py
> +                session.close()
Same comment with this session

2024-08-08 16:58 UTC, micah-prime requested changes
Looking good! Couple of minor asks

2024-08-08 17:03 UTC, micah-prime commented
> Just a quick reminder to keep track of the changes and maybe start a manual CHANGELOG.md for now until I get back to #85 and automate this?

I'm going to merge #85 for now so we can update that. Then I'll  merge into this branch so we have a changelog to update

2024-08-13 15:52 UTC, micah-prime approved these changes

2024-08-13 15:53 UTC, merged